# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "learning-app-dev"
client_id = "dd3bc30033372c79c233ace3645be7b2"
application_url = "https://icon-stand-spanking-pvc.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://icon-stand-spanking-pvc.trycloudflare.com/auth/callback",
  "https://icon-stand-spanking-pvc.trycloudflare.com/auth/shopify/callback",
  "https://icon-stand-spanking-pvc.trycloudflare.com/api/auth/callback",
  "https://icon-stand-spanking-pvc.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "hydrogen-building.myshopify.com"
